version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: payslip-postgres10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: payslips_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5201:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payslip-net

  backend:
    build:
      context: ./Backend
    container_name: payslip-backend10
    ports:
      - "3201:3201"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=payslips_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payslip-net

  employee-slip:
    build:
      context: ./Employee-slip
    container_name: payslip-employee10
    ports:
      - "8002:80"
    environment:
      - BACKEND_URL=http://backend:3201
    depends_on:
      - backend
    networks:
      - payslip-net

  hr-slip:
    build:
      context: ./HR-slip
    container_name: payslip-hr10
    ports:
      - "8003:80"
    environment:
      - BACKEND_URL=http://backend:3201
    depends_on:
      - backend
    networks:
      - payslip-net

volumes:
  pgdata:

networks:
  payslip-net:
    driver: bridge
